name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: "postgres"
        ports:
          - '5433:5433'
        env:
          POSTGRES_USER: "diper"
          POSTGRES_PASSWORD: "diper"
          POSTGRES_DB: "diper"

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --configuration Release
      env:
        ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=diper;User id=diper;Password=diper